ACQ-2216: adding default "no" value to Consent & ConsentLite input checkbox fields
Financial-Times/n-profile-ui pull request #128
Opened 2023-05-29 09:23 UTC by maguero

## Description

Some time ago, consent components (`Consent` and `ConsentLite`) had been modified to move from html `radio-button` to `checkbox` input fields.

### The Problem

If a checkbox is unchecked when its form is submitted, neither the name nor the value is submitted to the server.
Currently, all repos using `Consent` and `ConsentLite` are not receiving the "no" value when they are unchecked. That means that the unchecked consents are not sent through the Consent API and then FT doesn't know if the consents were presented to the user (only the checked consents are sent today).

In addition, when all consents in the page are unchecked, then the server is throwing an error when calling [buildConsentRecord](https://github.com/Financial-Times/n-profile-ui/blob/v14.1.2/src/js/helpers.ts#LL126C17-L126C35) method because no consents are found in the body request.

```Javascript
  if (!consentRecord) {
    throw new Error('Found no valid consents');
  }
```
See https://financialtimes.atlassian.net/browse/ACQ-2204 for examples.

### The Solution

The solution proposed by this PR is to create a `<input type="hidden">` within the form with a value indicating an unchecked state, using the same "name" property to ensure receiving a default "no" value when the checkbox is unchecked.

The side effect is that the server side is receiving an array of value instead of a single string only when the checkbox is checked.

Example:
- consent-enhancement-byEmail --> checked ✅ 
- consent-marketing-byEmail --> unchecked 🔲 

![image](https://github.com/Financial-Times/n-profile-ui/assets/13876273/770c8aa0-a066-48a5-b7f7-04c256c3c551)

In order to mitigate a possible error handing this values the solution includes a new property to enable this behaviour: `includeUncheckedValues`. As a second measure, `buildConsentRecord` method is also modified to handle both cases: string or array of string values, looking for `yes` occurrences.

## Ticket
- https://financialtimes.atlassian.net/browse/ACQ-2204
- https://financialtimes.atlassian.net/browse/ACQ-2216

2023-05-29 09:28 UTC, maguero commented on test/unit/helpers.spec.ts
> +			'consent-categoryB-channel2': ['yes', 'no'],
Modifying this tests assert makes it to cover the new option about the array of string values 😆

2023-05-29 09:59 UTC, JuanTincho reviewed
I noticed that the `ToggleSwitch` component is being duplicated in `Consent` and `ConsentLite` components, could we extract it to another file and reuse it?

2023-05-29 09:59 UTC, JuanTincho commented on src/js/server/components/Consent.tsx
> +	includeUncheckedValues: boolean;
Do we need this? I think we can change it as we are going to fix everything inside this repo and if other teams are using it as it is, they have the bug as well.

2023-05-29 13:04 UTC, maguero commented on src/js/server/components/Consent.tsx
> +	includeUncheckedValues: boolean;
> I noticed that the `ToggleSwitch` component is being duplicated in `Consent` and `ConsentLite` components, could we extract it to another file and reuse it?

Good catch! Yes, let's use this PR to also extract that component and reuse it for both `Consent` and `ConsentLite`.
Thanks!

2023-05-29 13:06 UTC, maguero commented
> I noticed that the `ToggleSwitch` component is being duplicated in `Consent` and `ConsentLite` components, could we extract it to another file and reuse it?

Good catch! Yes, let's use this PR to also extract that component and reuse it for both `Consent` and `ConsentLite`.
Thanks @JuanTincho !

2023-05-30 12:24 UTC, JuanTincho requested changes
Thank you for this! 

I've left a few comments 😄

2023-05-30 12:24 UTC, JuanTincho commented on src/js/helpers.ts
> +		return Array.from(value).includes('yes');
Is `Array.from()` needed here? We already checked if it's an array? 
```suggestion
		return value.includes('yes');
```

2023-05-30 12:24 UTC, JuanTincho commented on src/js/helpers.ts
> +					status: convertStringConsentToBoolean(value),
Nitpick: Would a name `getConsentStatus` for the function make more sense for this function?

2023-05-30 12:24 UTC, JuanTincho commented on src/js/server/components/ToggleSwitch.tsx
> +	isLite = false,
I don't see this prop `isLite` being passed in the `ConsentLite` component?

2023-05-30 13:01 UTC, maguero commented on src/js/helpers.ts
> +					status: convertStringConsentToBoolean(value),
definitely a better name! thanks 💙

2023-05-30 13:32 UTC, JuanTincho commented on src/js/server/components/ConsentLite.tsx
> +								isLite={true}
```suggestion
								isLite
```

2023-05-30 13:49 UTC, maguero commented on src/js/server/components/ConsentLite.tsx
> +								isLite={true}
ohhh, we learn things every day 🤓 . I didn't know that no values is sending `true` as default.
Doc: https://legacy.reactjs.org/docs/jsx-in-depth.html#props-default-to-true (I didn't find it on the new documentation 😢 )

btw, I would say we can keep the assignation just to avoid confusions.

2023-05-31 07:39 UTC, oliverturner approved these changes
Neat solution!

2023-05-31 07:44 UTC, merged